- hosts: local
  connection: local
  remote_user: root
  sudo: yes
  vars:
      home_path: "/home/owalid/rogerskyline1"
  tasks:
# install basic packages
    - name: Update packages
      shell: sudo apt-get clean && sudo apt-get -y upgrade && sudo apt-get -y update
    - name: Install base packages
      apt: name={{ item }} state=installed
      with_items:
          - sudo
          - fail2ban
          - iptables-persistent
          - portsentry
          - git
          - vim
# ssh config
    - name: Cpy config ssh
      copy:
          src: /home/owalid/rogerskyline1/config/sshd_config
          dest: /etc/ssh/sshd_config
    - name: restart ssh
      service:
          name: sshd
          state: restarted
# cron config
    - name: Update
      cron:
          name: "update"
          job: "cron/update.sh"
    - name: Update
      cron:
          name: "update"
          special_time: reboot
          job: "cron/update.sh"
    - name: Check change
      cron:
          name: "check change"
          job: "cron/check.sh"
    - name: restart cron
      service:
          name: cron
          state: restarted
# f2ban config
    - name: fail2ban config (jail)
      copy:
          src: /home/owalid/rogerskyline1/config/jail.conf
          dest: /etc/fail2ban/jail.conf
    - name: fail2ban config (fail2ban.d)
      copy:
          src: /home/owalid/rogerskyline1/config/fail2ban.conf
          dest: /etc/fail2ban/fail2ban.conf
    - name: restart f2ban
      service:
          name: fail2ban
          state: restarted
# Copy scripts
    - name: copy script pull
      copy:
          src: "{{ home_path }}/script/pull.sh"
          dest: "{{ home_path }}/pull.sh"
    - name: copy iptables scripts
      copy:
          src: "{{ home_path }}/script/iptables.sh"
          dest: "{{ home_path }}/iptables.sh"
# iptables config
    - name: script iptables
      shell: sh "{{ home_path }}/iptables.sh"
    
    - name: save iptables
      shell: iptables-save > /etc/iptables/rules.v4 && iptables-save > /etc/iptables/rules.v6

    - name: restart network
      service:
          name: networking
          state: restarted
# clone website
    - name: script clone
      copy:
          src: "{{ home_path }}/movie_search"
          dest: /var/www/html

# apache config
    - name: config apache
      template:
          src: templates/apache.conf
          dest: /etc/apachache2/apache2.conf
    - name: restart apache
      service:
          name: httpd
          state: restarted
